# GitHub Actions Workflow for Vertex AI TFX Pipeline Deployment
name: Deploy Vertex AI TFX Pipeline
on:
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"

env:
  ENVIRONMENT: dev
  PROJECT_ID: sinuous-myth-447220-m2
  SERVICE_ACCOUNT: sinuous-sa-github@sinuous-myth-447220-m2.iam.gserviceaccount.com
  REGION: europe-west4
  DOCKER_REPO: europe-west4-docker.pkg.dev/sinuous-myth-447220-m2/docker-repo
  WORKLOAD_ID_PROVIDER: projects/871125057680/locations/global/workloadIdentityPools/gh-pool2/providers/gh-provider
  GCS_BUCKET: gs://${bucket_name}/creditcards/compiled_pipelines/

jobs:
  run-pipeline:
    name: Deploy Vertex AI TFX Pipeline
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      # Step 2: Authenticate with Google Cloud
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ env.WORKLOAD_ID_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: 7200s

      # Step 3: Compile the TFX Pipeline
      - name: Compile TFX Pipeline
        uses: docker://python:3.9
        with:
          entrypoint: python
        args:
          - build/utils.py
          - --mode
          - compile-pipeline
          - --pipeline-name
          - example_pipeline
        working-directory: ./ # Root directory of the TFX pipeline
        id: compile-pipeline

      # Step 4: Upload Compiled Pipeline JSON to GCS
      - name: Upload Compiled Pipeline to GCS
        uses: docker://gcr.io/cloud-builders/gsutil
        with:
          args:
            - cp
            - example_pipeline.json
            - ${{ env.GCS_BUCKET }}
        working-directory: ./ # Root directory of the TFX pipeline
        id: upload-pipeline
