name: Deploy Vertex AI TFX Pipeline
on:
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"

env:
  ENVIRONMENT: dev
  PROJECT_ID: sinuous-myth-447220-m2
  SERVICE_ACCOUNT: admin-157@sinuous-myth-447220-m2.iam.gserviceaccount.com
  REGION: us-east1
  DOCKER_REPO: europe-west4-docker.pkg.dev/sinuous-myth-447220-m2/docker-repo
  WORKLOAD_ID_PROVIDER: projects/871125057680/locations/global/workloadIdentityPools/gh-pool2/providers/gh-provider
  GCS_BUCKET: gs://sinuous-creditcards-dev

jobs:
  run-pipeline:
    name: Deploy Vertex AI TFX Pipeline
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set Up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
           pip install kfp==1.8.16
          pip install google-cloud-videointelligence==2.7.0
          pip install google-cloud-spanner==3.50.0
          pip install tfx
          pip install requests_toolbelt==0.10.1
          pip install urllib3==1.26.6

      # Step 4: Authenticate with Google Cloud
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ env.WORKLOAD_ID_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          access_token_lifetime: 7200s

      # Step 5: Compile the Pipeline
      - name: Compile Pipeline
        run: |
          cd ./tfx-pipeline
          python build/utils.py compile-pipeline

      # Step 6: Upload Compiled Pipeline to GCS
      - name: Upload Compiled Pipeline
        run: |
          cd ./tfx-pipeline
          gsutil cp example_pipeline.yaml ${{ env.GCS_BUCKET }}
