steps:
  # Step 1: Install dependencies
  - name: "python:3.9"
    entrypoint: pip
    args:
      ["install", "-r", "src/pipeline_triggering/requirements.txt", "--user"]
    dir: "./" # Root directory of the tfx-pipeline structure
    id: "Install Dependencies"

  # Step 2: Run the pipeline
  - name: "python:3.9"
    entrypoint: "python"
    args:
      - build/utils.py
      - --mode
      - run-pipeline
      - --pipeline-json
      - gs://your-bucket-name/compiled_pipelines/example_pipeline.json
      - --region
      - your-region
      - --project
      - your-project-id
    dir: "./" # Root directory of the tfx-pipeline structure
    id: "Run Pipeline"
