name: Run Vertex AI Pipeline

on:
  workflow_dispatch: # Allow manual execution of the workflow

jobs:
  run-pipeline:
    name: Execute Vertex AI Pipeline
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install required Python packages
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-cloud-aiplatform google-cloud-storage kfp google-cloud-pipeline-components

      # Step 4: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ secrets.GCLOUD_KEY }}"
        run: |
          echo "${{ secrets.GCLOUD_KEY }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          rm key.json  # Remove credentials for security

      # Step 5: Execute Pipeline
      - name: Run Pipeline
        env:
          PROJECT_ID: "${{ secrets.PROJECT_ID }}"
          REGION: "${{ secrets.REGION }}"
          BUCKET_URI: "${{ secrets.BUCKET_URI }}"
        run: |
          python util.py run
